seed_everything: 777
mode: predict
weights_path: /app/model_weights/scaleface_vb2/scaleface_vb2.ckpt
trainer:
  _target_: pytorch_lightning.Trainer
  callbacks:
  - _target_: training.models.scf.Prediction_writer
    output_dir: /app/datasets/vb-clean_ident
    file_name: scaleface_vb2
    write_interval: epoch
  max_epochs: 2
  accelerator: gpu
  devices: 1
  num_sanity_val_steps: 0
  log_every_n_steps: 3
  default_root_dir: outputs/scaleface_vb2
  val_check_interval: 0.1
  enable_checkpointing: true
model:
    _target_: training.models.scaleface.ScaleFace
    backbone:
        _target_: training.models.lightning_wrappers.EmbModel
    head:
        _target_: training.models.heads.SCFHead
        convf_dim: 1024
        latent_vector_size: 4096
    scaleface_loss:
        _target_: training.models.losses.ArcFaceLoss #ArcFaceScale
        m: 0.5
    softmax_weights:
        _target_: training.models.scf.SoftmaxWeights
        softmax_weights_path: "/app/datasets/VB2_11_embs/softmax_weight.pt"
        radius: 1
    optimizer_params:
        optimizer_path: torch.optim
        optimizer_name: AdamW
        params:
            lr: 3e-2 #3e-5
            weight_decay: 5e-4
    scheduler_params:
        scheduler: OneCycleLR
        params:
            max_lr: 3e-3
            steps_per_epoch: 2629
            epochs: 2
            div_factor: 1e1
            final_div_factor: 1e2
        interval: step
    permute_batch: False


data:
    _target_: training.dataset_classes.lightning_datasets.UncertaintyDataModule
    train_dataset:
        _target_: training.dataset_classes.lightning_datasets.VoxBlinkEmbeddingsDataset
        root_dir: /app/datasets/VB2_11_embs
    predict_dataset:
        _target_: training.dataset_classes.lightning_datasets.VoxBlinkEmbeddingsDataset
        root_dir: /app/datasets/VB1_embs

    batch_size: 1060
    num_workers: 20