# DO NOT CHANGE
hydra:
  run:
    dir: ${exp_dir}
exp_dir: outputs/latex_tables

defaults:
  - _self_
  - pretty_names@pretty_name.dataset: dataset_pretty_name
  - pretty_names@pretty_name.model: model_pretty_name
  - pretty_names@pretty_name.column: column_pretty_name
  - meta_data@metric_order: metric_order


datasets: ["IJBC", "IJBB", "whale", "large_12k-perspk5"]

task: filter

# CHANGE
metric_table_path: /app/outputs/experiments/filter/open_set_identification/{dataset}/filter_tabels/f1_class_prr_filtering.csv

caption: >
  Prediction Rejection Ratios (PRR, $\uparrow$) for $F_1$ filtering curve for the four considered datasets IJB-C, IJB-B, Whale, VB-Eval-L.
  
fix_table: False
table_lable: "tab:${task}"
round_num: 2
table_size: footnotesize
tabcolsep: 2
use_adjustbox: False

sort_models_with: "used_models"

used_columns_dict:
  filter:
    whale:
      [
        "models",
        "FAR=0.05",
        "FAR=0.1",
        "FAR=0.2",
      ]
    IJBB:
      [
        "models",
        "FAR=0.05",
        "FAR=0.1",
        "FAR=0.2",
      ]
    IJBC:
      [
        "models",
        "FAR=0.05",
        "FAR=0.1",
        "FAR=0.2"
      ]
    large_12k-perspk5:
      [
        "models",
        "FAR=0.01",
        "FAR=0.05",
        "FAR=0.1",
      ]


