# DO NOT CHANGE
hydra:
  run:
    dir: ${exp_dir}
exp_dir: outputs/latex_tables

defaults:
  - _self_
  - pretty_names@pretty_name.dataset: dataset_pretty_name
  - pretty_names@pretty_name.model: model_pretty_name
  - pretty_names@pretty_name.column: column_pretty_name
  - meta_data@metric_order: metric_order


#datasets: ["yahoo", "agnews", "dbpedia"]
datasets: ["pan_test", "clinc150"]

task: filter

# CHANGE
metric_table_path: /app/outputs/experiments/osr_text/open_set_identification/{dataset}/filter_tabels/f1_class_prr_filtering.csv

caption: >
  Prediction Rejection Ratios (PRR, $\uparrow$) for $F_1$ filtering curve for PAN authorship attribution and CLINC150 intent classification datasets.

# caption: >
#   Prediction Rejection Ratios (PRR, $\uparrow$) for $F_1$ filtering curve for three topic classification datasets.

  
fix_table: False
table_lable: "tab:${task}"
round_num: 2
table_size: footnotesize
tabcolsep: 2
use_adjustbox: False

sort_models_with: "used_models"

used_columns_dict:
  filter:
    dbpedia:
      [
        "models",
        "FAR=0.1",
        "FAR=0.2",
        "FAR=0.3",
        "FAR=0.4",
        "FAR=0.5",
      ]
    yahoo:
      [
        "models",
        "FAR=0.1",
        "FAR=0.2",
        "FAR=0.3",
        "FAR=0.4",
        "FAR=0.5",
      ]
    agnews:
      [
        "models",
        "FAR=0.1",
        "FAR=0.2",
        "FAR=0.3",
        "FAR=0.4",
        "FAR=0.5",
      ]
    clinc150:
      [
        "models",
        "FAR=0.1",
        "FAR=0.2",
        "FAR=0.3",
        "FAR=0.4",
        "FAR=0.5",
      ]
    pan_test:
      [
        "models",
        "FAR=0.1",
        "FAR=0.2",
        "FAR=0.3",
        "FAR=0.4",
        "FAR=0.5",
      ]

    whale:
      [
        "models",
        "FAR=0.05",
        "FAR=0.1",
        "FAR=0.2",
      ]
    IJBB:
      [
        "models",
        "FAR=0.05",
        "FAR=0.1",
        "FAR=0.2",
      ]
    IJBC:
      [
        "models",
        "FAR=0.05",
        "FAR=0.1",
        "FAR=0.2"
      ]
    large_12k-perspk5:
      [
        "models",
        "FAR=0.01",
        "FAR=0.05",
        "FAR=0.1",
      ]


