name: base
channels:
  - pytorch
  - anaconda
  - conda-forge
  - defaults
dependencies:
  - psutil
  - ipykernel
  - python=3.9.7
  - conda-forge::scikit-image
  - conda-forge::termcolor
  - conda-forge::tensorboard
  - conda-forge::black
  - conda-forge::hydra-core
  - conda-forge::numexpr
  - anaconda::ipython
  - anaconda::path
  - pip
  - openblas-devel
  - tqdm
  - nose
  - cython
  - optuna-integration[pytorch_lightning]
  - pysoundfile
  - pip:
    - torch==2.1.1
    - ipywidgets
    - python_speech_features
    - scikit-learn-intelex
    - numexpr
    - wandb
    - onnx
    - torchaudio
    - thop
    - torch-summary
    - optuna
    - timm
    - onnx2torch
    - albumentations
    - tabulate
    - onnxruntime-gpu
    - glob2
    - jsonargparse[signatures]
    - torchvision
    - progressbar2
    - exman
    - easydict
    - pytorch-lightning==2.0.0
    - opencv-python
    - mxnet-mkl==1.6.0
    - bcolz-zipline
    - "dask[array]"
    - botorch
    - plotly
    - numpy==1.23.1
    - PyYAML
    - scipy
    - pydrive2
    - pandas
    - scikit-learn
    - tqdm
    - imageio
    - matplotlib
    - seaborn
    - scikit-learn-intelex
    - "black[jupyter]"
    - geotorch