hydra:
  run:
    dir: ${exp_dir}

exp_dir: outputs/experiments/filtering_plots
use_two_galleries: False
recompute_template_pooling: True
metric_pretty_name_path: /app/configs/latex_tables/pretty_names/column_pretty_name_unc.yaml
create_pool_plot: False

test_datasets:
  # - _target_: evaluation.test_datasets.FaceRecogntionDataset
  #   dataset_name: ms1m
  #   dataset_path: /app/datasets/ms1m_ident
  - _target_: evaluation.test_datasets.FaceRecogntionDataset
    dataset_name: whale
    dataset_path: /app/datasets/whale
  # - _target_: evaluation.test_datasets.FaceRecogntionDataset
  #   dataset_name: IJBB
  #   dataset_path: /app/datasets/arcface_ijb/IJBB

  # - _target_: evaluation.test_datasets.FaceRecogntionDataset
  #   dataset_name: IJBC
  #   dataset_path: /app/datasets/arcface_ijb/IJBC

  # - _target_: evaluation.test_datasets.FaceRecogntionDataset
  #   dataset_name: lfw
  #   dataset_path: /app/datasets/lfw_ident


  # - _target_: evaluation.test_datasets.FaceRecogntionDataset
  #   dataset_name: survFace
  #   dataset_path: /app/datasets/QMUL-SurvFace/Face_Identification_Test_Set


calibration_set:
  _target_: evaluation.test_datasets.FaceRecogntionDataset
  dataset_name: whale_val
  dataset_path: /app/datasets/whale_val


open_set_identification_metrics:
  - _target_: evaluation.metrics.ErrorDistribution
    plot_save_dir: ${exp_dir}
    value_types: [0,1, 2, 3, 4, 5]
  - _target_: evaluation.metrics.DirFar

fractions: [0, 0.1, 20]

open_set_identification_uncertainty_metrics:
  - _target_: evaluation.uncertainty_metrics.DisposeBasedOnUnc
    fractions: ${fractions}
    metric_to_monitor:
      _target_: evaluation.metrics.FrrFarIdent
  
  - _target_: evaluation.uncertainty_metrics.DisposeBasedOnUnc
    fractions: ${fractions}
    metric_to_monitor:
      _target_: evaluation.metrics.DirFar

  - _target_: evaluation.uncertainty_metrics.DisposeBasedOnUnc
    fractions: ${fractions}
    metric_to_monitor:
      _target_: evaluation.metrics.F1_classic

default_beta: 0.5
far_list: [0.1]
display_oracle_curve: True

open_set_identification_methods:


  - embeddings: scf
    gallery_template_pooling_strategy:
      _target_: evaluation.template_pooling_strategies.PoolingDefault  #PoolingConcentration, PoolingDefault
    probe_template_pooling_strategy:
      _target_: evaluation.template_pooling_strategies.PoolingDefault #PoolingProb
    use_detector_score: False
    recognition_method:
      _target_: evaluation.open_set_methods.posterior_prob_based.PosteriorProbability
      distance_function: 
        _target_: evaluation.distance_functions.open_set_identification.CosineSim
      class_model: power
      far: ${far_list}
      beta: ${default_beta}
      uncertainty_type: maxprob
      alpha: 1 # when 1, only scf unc is used
      aggregation: sum
      T: 3
      T_data_unc: 1
    pretty_name: "$u_{SCF}$"


  - embeddings: scf
    gallery_template_pooling_strategy:
      _target_: evaluation.template_pooling_strategies.PoolingDefault
    probe_template_pooling_strategy:
      _target_: evaluation.template_pooling_strategies.PoolingDefault
    use_detector_score: False
    recognition_method:
      _target_: evaluation.open_set_methods.score_function_based.SimilarityBasedPrediction
      distance_function: 
        _target_: evaluation.distance_functions.open_set_identification.CosineSim
      acceptance_score: 
        _target_: evaluation.confidence_functions.MaxSimilarity_confidence
      uncertainty_function:
        _target_: evaluation.open_set_methods.uncertainty_functions.BernoulliVariance
      alpha: 0
      beta_calib: True
    pretty_name: "$u_{baseline}$"

  - embeddings: scf
    gallery_template_pooling_strategy:
      _target_: evaluation.template_pooling_strategies.PoolingDefault  #PoolingConcentration, PoolingDefault
    probe_template_pooling_strategy:
      _target_: evaluation.template_pooling_strategies.PoolingDefault #PoolingProb
    use_detector_score: False
    recognition_method:
      _target_: evaluation.open_set_methods.posterior_prob_based.PosteriorProbability
      distance_function: 
        _target_: evaluation.distance_functions.open_set_identification.CosineSim
      class_model: power
      far: ${far_list}
      beta: ${default_beta}
      uncertainty_type: maxprob
      alpha: 0
      aggregation: sum
      T: 3
      T_data_unc: 1
    pretty_name: "$u_{power} (our)$"

  - embeddings: scf
    gallery_template_pooling_strategy:
      _target_: evaluation.template_pooling_strategies.PoolingDefault
    probe_template_pooling_strategy:
      _target_: evaluation.template_pooling_strategies.PoolingDefault
    use_detector_score: False
    recognition_method:
      _target_: evaluation.open_set_methods.score_function_based.SimilarityBasedPrediction
      distance_function: 
        _target_: evaluation.distance_functions.open_set_identification.CosineSim
      acceptance_score: 
        _target_: evaluation.confidence_functions.MaxSimilarity_confidence
      uncertainty_function:
        _target_: evaluation.open_set_methods.uncertainty_functions.BernoulliVariance
      alpha: 0.5
      calibration_set: ${calibration_set}
      embs_name: scf
    pretty_name: "$u_{baseline} + u_{SCF}$"


  - embeddings: scf
    gallery_template_pooling_strategy:
      _target_: evaluation.template_pooling_strategies.PoolingDefault  #PoolingConcentration, PoolingDefault
    probe_template_pooling_strategy:
      _target_: evaluation.template_pooling_strategies.PoolingDefault #PoolingProb
    use_detector_score: False
    recognition_method:
      _target_: evaluation.open_set_methods.posterior_prob_based.PosteriorProbability
      distance_function: 
        _target_: evaluation.distance_functions.open_set_identification.CosineSim
      class_model: power
      far: ${far_list}
      beta: ${default_beta}
      uncertainty_type: maxprob
      alpha: 0.5
      aggregation: sum
      T: 3
      T_data_unc: 1
      calibrate_unc: True
      calibrate_gallery_unc: True
      calibration_set: ${calibration_set}
      calibration_embs_name: "scf"
    pretty_name: "$u_{power} + u_{SCF} (our)$"

  - embeddings: scf
    gallery_template_pooling_strategy:
      _target_: evaluation.template_pooling_strategies.PoolingDefault
    probe_template_pooling_strategy:
      _target_: evaluation.template_pooling_strategies.PoolingDefault
    use_detector_score: False
    recognition_method:
      _target_: evaluation.open_set_methods.score_function_based.SimilarityBasedPrediction
      distance_function: 
        _target_: evaluation.distance_functions.open_set_identification.CosineSim
      acceptance_score: 
        _target_: evaluation.confidence_functions.MaxSimilarity_confidence
      uncertainty_function:
        _target_: evaluation.open_set_methods.uncertainty_functions.RandomScore
      alpha: 0
    pretty_name: "$u_{random}$"


  - embeddings: scf
    gallery_template_pooling_strategy:
      _target_: evaluation.template_pooling_strategies.PoolingDefault
    probe_template_pooling_strategy:
      _target_: evaluation.template_pooling_strategies.PoolingDefault
    use_detector_score: False
    recognition_method:
      _target_: evaluation.open_set_methods.score_function_based.SimilarityBasedPrediction
      distance_function: 
        _target_: evaluation.distance_functions.open_set_identification.CosineSim
      acceptance_score: 
        _target_: evaluation.confidence_functions.MaxSimilarity_confidence
      uncertainty_function:
        _target_: evaluation.open_set_methods.uncertainty_functions.OracleScore
      alpha: 0
      oracle_predictions: True
    pretty_name: "$u_{oracle}$"













