hydra:
  run:
    dir: ${exp_dir}

exp_dir: outputs/experiments/osr_clinc150
use_two_galleries: False
recompute_template_pooling: True
metric_pretty_name_path: /app/configs/latex_tables/pretty_names/column_pretty_name.yaml
create_pool_plot: False

test_datasets:
  - _target_: evaluation.test_datasets.FaceRecogntionDataset
    dataset_name: clinc150
    dataset_path: /app/datasets/clinc150_test



dataset_name_to_calibration_set:
  IJBB: ${calibration_sets.ijb_val}
  IJBC: ${calibration_sets.ijb_val}
  whale: ${calibration_sets.whale_val}
  large_12k-perspk5: ${calibration_sets.voxblink_val} 
  clinc150: ${calibration_sets.clinc150_val} 
dataset_name_to_T_scale:
  IJBB: 7
  IJBC: 7
  whale: 20
  large_12k-perspk5: 20
  clinc150: 50

calibration_sets:
  ijb_val:
    _target_: evaluation.test_datasets.FaceRecogntionDataset
    dataset_name: ms1m
    dataset_path: /app/datasets/ms1m_ident
  voxblink_val:
    _target_: evaluation.test_datasets.FaceRecogntionDataset
    dataset_name: medium_1.2k-perspk5
    dataset_path: /app/datasets/vb-clean_ident/Medium_1.2k/perspk5
  whale_val:
    _target_: evaluation.test_datasets.FaceRecogntionDataset
    dataset_name: whale_val
    dataset_path: /app/datasets/whale_val
  clinc150_val:
    _target_: evaluation.test_datasets.FaceRecogntionDataset
    dataset_name: clinc150_val
    dataset_path: /app/datasets/clinc150_val
    # _target_: evaluation.test_datasets.FaceRecogntionDataset
    # dataset_name: yahoo_answers
    # dataset_path: /app/datasets/text-ident/yahoo_answers



open_set_identification_metrics:
  - _target_: evaluation.metrics.ErrorDistribution
    plot_save_dir: ${exp_dir}
    value_types: [0, 1, 2, 3, 4, 5]
  - _target_: evaluation.metrics.FnirFpir

fractions: [0, 0.5, 20]

open_set_identification_uncertainty_metrics:
  - _target_: evaluation.uncertainty_metrics.DisposeBasedOnUnc
    fractions: ${fractions}
    metric_to_monitor:
      _target_: evaluation.metrics.FrrFarIdent
  
  - _target_: evaluation.uncertainty_metrics.DisposeBasedOnUnc
    fractions: ${fractions}
    metric_to_monitor:
      _target_: evaluation.metrics.FnirFpir

  - _target_: evaluation.uncertainty_metrics.DisposeBasedOnUnc
    fractions: ${fractions}
    metric_to_monitor:
      _target_: evaluation.metrics.F1_classic

beta_list: [0.5] # [1e-5] #[0.5]
far_list: [0.2] #[0.2, 0.3, 0.4, 0.5] #[0.01, 0.05, 0.1, 0.2] #[0.1, 0.2] #
display_oracle_curve: True

open_set_identification_methods:

  - embeddings: scf
    gallery_template_pooling_strategy:
      _target_: evaluation.template_pooling_strategies.PoolingDefault
    probe_template_pooling_strategy:
      _target_: evaluation.template_pooling_strategies.PoolingDefault
    recognition_method:
      _target_: evaluation.open_set_methods.score_function_based.SimilarityBasedPrediction
      distance_function: 
        _target_: evaluation.distance_functions.open_set_identification.CosineSim
      acceptance_score: 
        _target_: evaluation.confidence_functions.MaxSimilarity_confidence
      uncertainty_function:
        _target_: evaluation.open_set_methods.uncertainty_functions.BernoulliVariance
      alpha: 0
      calib_strategy: "norm_val"
    pretty_name: "AccScr"


  # - embeddings: scf
  #   gallery_template_pooling_strategy:
  #     _target_: evaluation.template_pooling_strategies.Identity
  #   probe_template_pooling_strategy:
  #     _target_: evaluation.template_pooling_strategies.PoolingDefault
  #   recognition_method:
  #     _target_: evaluation.open_set_methods.score_function_based.SimilarityBasedPrediction
  #     distance_function: 
  #       _target_: evaluation.distance_functions.open_set_identification.MahalanobisDistance
  #     acceptance_score: 
  #       _target_: evaluation.confidence_functions.MaxSimilarity_confidence
  #     uncertainty_function:
  #       _target_: evaluation.open_set_methods.uncertainty_functions.BernoulliVariance
  #     alpha: 0
  #     calib_strategy: "norm_val"
  #     predictor: AccScore
  #   pretty_name: "AccScr Mahalanobis"


  - embeddings: scf
    gallery_template_pooling_strategy:
      _target_: evaluation.template_pooling_strategies.PoolingDefault
    probe_template_pooling_strategy:
      _target_: evaluation.template_pooling_strategies.PoolingDefault
    recognition_method:
      _target_: evaluation.open_set_methods.score_function_based.SimilarityBasedPrediction
      distance_function: 
        _target_: evaluation.distance_functions.open_set_identification.CosineSim
      acceptance_score: 
        _target_: evaluation.confidence_functions.MaxSimilarity_confidence
      uncertainty_function:
        _target_: evaluation.open_set_methods.uncertainty_functions.BernoulliVariance
      alpha: 1
      calib_strategy: "norm_val"
    pretty_name: "SCF"


  - embeddings: scf
    gallery_template_pooling_strategy:
      _target_: evaluation.template_pooling_strategies.PoolingDefault  
    probe_template_pooling_strategy:
      _target_: evaluation.template_pooling_strategies.PoolingDefault
    recognition_method:
      _target_: evaluation.open_set_methods.class_prob_models.MonteCarloPredictiveProb
      gallery_prior: power
      emb_unc_model: vMF
      beta: 0.5
      alpha: 0.5
      predict_T: 300
      pred_uncertainty_type: entropy
      far: null
      calibration_set: True
      calibration_embs_name: scf
      calibration_transform:
        _target_: evaluation.open_set_methods.calibration_methods.NNcalibration
        # model:
        #   _target_: evaluation.open_set_methods.calibration_methods.ExpTransform
        #   use_shift: True
        #   use_alpha: True
        model:
          _target_: evaluation.open_set_methods.calibration_methods.MLP
          hidden_size: 10 # 6
          num_layers: 4 # 3
          use_bn: True #False
        lr: 0.001
        epochs: 2000
        weight: 0
        use_norm: True
        train_weight: False
        #weight_loss_types: True
        weight_decay: 0.001
        normalize_kl_by_test: False 
        scheduler_params: 
          max_lr: 1e-3
          steps_per_epoch: 1
          div_factor: 1e1
          final_div_factor: 1e1
        log_dir: ${exp_dir}
    pretty_name: "HolUE"

  # - embeddings: scaleface
  #   gallery_template_pooling_strategy:
  #     _target_: evaluation.template_pooling_strategies.PoolingDefault
  #   probe_template_pooling_strategy:
  #     _target_: evaluation.template_pooling_strategies.PoolingDefault
  #   recognition_method:
  #     _target_: evaluation.open_set_methods.score_function_based.SimilarityBasedPrediction
  #     distance_function: 
  #       _target_: evaluation.distance_functions.open_set_identification.CosineSim
  #     acceptance_score: 
  #       _target_: evaluation.confidence_functions.MaxSimilarity_confidence
  #     uncertainty_function:
  #       _target_: evaluation.open_set_methods.uncertainty_functions.BernoulliVariance
  #     alpha: 1
  #     calib_strategy: "norm_val"
  #   pretty_name: "ScaleFace"



  # - embeddings: scf
  #   gallery_template_pooling_strategy:
  #     _target_: evaluation.template_pooling_strategies.PoolingDefault  
  #   probe_template_pooling_strategy:
  #     _target_: evaluation.template_pooling_strategies.PoolingDefault
  #   recognition_method:
  #     _target_: evaluation.open_set_methods.posterior_prob_based.PosteriorProbability
  #     distance_function: 
  #       _target_: evaluation.distance_functions.open_set_identification.CosineSim
  #     class_model: power
  #     far: ${far_list}
  #     beta: 0.5
  #     uncertainty_type: maxprob
  #     alpha: 0
  #     aggregation: sum
  #     predict_T: null
  #     T_data_unc: 1
  #   pretty_name: "GalUE"

  - embeddings: scf
    gallery_template_pooling_strategy:
      _target_: evaluation.template_pooling_strategies.PoolingDefault
    probe_template_pooling_strategy:
      _target_: evaluation.template_pooling_strategies.PoolingDefault
    recognition_method:
      _target_: evaluation.open_set_methods.score_function_based.SimilarityBasedPrediction
      distance_function: 
        _target_: evaluation.distance_functions.open_set_identification.CosineSim
      acceptance_score: 
        _target_: evaluation.confidence_functions.MaxSimilarity_confidence
      uncertainty_function:
        _target_: evaluation.open_set_methods.uncertainty_functions.RandomScore
      alpha: 0
    pretty_name: "Random"


  - embeddings: scf
    gallery_template_pooling_strategy:
      _target_: evaluation.template_pooling_strategies.PoolingDefault
    probe_template_pooling_strategy:
      _target_: evaluation.template_pooling_strategies.PoolingDefault
    recognition_method:
      _target_: evaluation.open_set_methods.score_function_based.SimilarityBasedPrediction
      distance_function: 
        _target_: evaluation.distance_functions.open_set_identification.CosineSim
      acceptance_score: 
        _target_: evaluation.confidence_functions.MaxSimilarity_confidence
      uncertainty_function:
        _target_: evaluation.open_set_methods.uncertainty_functions.OracleScore
      alpha: 0
      oracle_predictions: True
    pretty_name: "Oracle"



