"vMF": "vMF"
"HolUE MLP test": "HolUE-MLP test"
"HolUE MLP val": "HolUE-MLP val"
"HolUE sum val": "HolUE-sum val"
"HolUE sum test": "HolUE-sum test"
"Baseline": "Baseline"
"vMF+SFC": "vMF+SFC" 
"SCF": "SCF"
"ScaleFace": "ScaleFace"
"PFE": "PFE" 
"Be": "Be"
"AccScr": "AccScr"
"GalUE": "GalUE"
"HolUE": "HolUE"
"Be+SCF": "Be+SCF" 
"vMF-log+SFC": "vMF-log+SFC"
