"vMF": "vMF"
"HolUE T scale and shift": "T scale and shift"
"HolUE T scale and alpha": "T scale and weight"
"HolUE T scale, shift and alpha": "T scale, shift and weight"
"HolUE T scale": "T scale"
"HolUE shift and alpha": "shift and alpha"
"HolUE S shift": "shift"
"HolUE alpha": "alpha"
"HolUE MLP": "MLP"
"HolUE MLP test": "HolUE-MLP test"
"HolUE MLP val": "HolUE-MLP val"
"HolUE sum val": "HolUE-sum val"
"HolUE sum test": "HolUE-sum test"
"Baseline": "Baseline"
"vMF+SFC": "vMF+SFC" 
"SCF": "SCF"
"ScaleFace": "ScaleFace"
"PFE": "PFE" 
"Be": "Be"
"AccScr": "AccScr"
"AccScr Mahalanobis": "Mahalanobis"
"GalUE": "GalUE"
"HolUE": "HolUE"
"Be+SCF": "Be+SCF" 
"vMF-log+SFC": "vMF-log+SFC"
