seed_everything: 777
mode: train
trainer:
  _target_: pytorch_lightning.Trainer
  logger:
    _target_: pytorch_lightning.loggers.mlflow.MLFlowLogger
    experiment_name: "CIFAR10N arcface"
    run_name: "Clean Arcface cifar10N 32x32"
  callbacks:
  - _target_: pytorch_lightning.callbacks.ModelCheckpoint 
    every_n_epochs: 1
    dirpath: outputs/arcface_cifar10N_32x32/filtered_dataset
    save_last: True
  - _target_: pytorch_lightning.callbacks.LearningRateMonitor
    logging_interval: "step"
  max_epochs: 40
  accelerator: gpu
  devices: 1
  log_every_n_steps: 3
  default_root_dir: outputs/arcface_cifar10N_32x32/filtered_dataset
  val_check_interval: 75 #125
  check_val_every_n_epoch: 1
  enable_checkpointing: true
  
model:
    _target_: training.models.arcface.MetricLearningModel
    backbone:
        _target_: training.models.lightning_wrappers.ResNet
        resnet_name: iresnet18_normalized
        weights: False
        learnable: True
        fc_scale: 4
        num_features: 64
    loss:
        _target_: training.models.losses.ArcFaceLoss
        s: 3
    num_labels: 10
    num_features: 64
    scheduler_params:
        scheduler: OneCycleLR
        params:
            max_lr: 1e-2
            steps_per_epoch: 75 # 125
            epochs: 40
            div_factor: 1e1
            final_div_factor: 1e1
        interval: step
    weight_decay: 1e-3


data:
    _target_: training.dataset_classes.lightning_datasets.UncertaintyDataModule
    train_dataset:
        _target_: training.dataset_classes.lightning_datasets.CIFAR_N
        root_dir: /app/datasets/cifar10
        ds_name: CIFAR10
        cosine_sim_path: /app/model_weights/cifar10N/train_cifar_10N_cosine_sim.npy
        angle: 25
        use_augments: False
    validation_dataset:
        _target_: training.dataset_classes.lightning_datasets.CIFAR
        root_dir: /app/datasets/cifar10
        train: False
        ds_name: CIFAR10

    batch_size: 400
    num_workers: 20