seed_everything: 777
mode: train
trainer:
  _target_: pytorch_lightning.Trainer
  logger:
    _target_: pytorch_lightning.loggers.WandbLogger
    project: "CIFAR100N"
    name: "Arcface cifar10 N"
  callbacks:
  - _target_: pytorch_lightning.callbacks.ModelCheckpoint 
    every_n_epochs: 1
    dirpath: outputs/arcface_cifar10N/noisy_dataset
    save_last: True
  - _target_: pytorch_lightning.callbacks.LearningRateMonitor
    logging_interval: "step"
#   - _target_: training.models.scf.Prediction_writer
#     output_dir: /app/cache/features/
#     file_name: scf_2epoch_embs
#     write_interval: epoch
  max_epochs: 40
  accelerator: gpu
  devices: 1
#   num_sanity_val_steps: 0
  log_every_n_steps: 3
  default_root_dir: outputs/arcface_cifar10N/noisy_dataset
  val_check_interval: 125
  check_val_every_n_epoch: 1
  enable_checkpointing: true
  
model:
    _target_: training.models.arcface.MetricLearningModel
    backbone:
        _target_: training.models.lightning_wrappers.ResNet
        resnet_name: iresnet18_normalized
        weights: False
        learnable: True
    loss:
        _target_: training.models.losses.ArcFaceLoss
        s: 4
    num_labels: 10 #10 #100
    num_features: 512
    scheduler_params:
        scheduler: OneCycleLR
        params:
            max_lr: 3e-3
            steps_per_epoch: 125
            epochs: 40
            div_factor: 1e1
            final_div_factor: 1e2
        interval: step
    weight_decay: 1e-3


data:
    _target_: training.dataset_classes.lightning_datasets.UncertaintyDataModule
    # train_dataset:
    #     _target_: training.dataset_classes.lightning_datasets.CIFAR
    #     root_dir: /app/datasets/cifar10
    #     train: True
    #     ds_name: CIFAR10
    # validation_dataset:
    #     _target_: training.dataset_classes.lightning_datasets.CIFAR
    #     root_dir: /app/datasets/cifar10
    #     train: False
    #     ds_name: CIFAR10
    # train_dataset:
    #     _target_: training.dataset_classes.lightning_datasets.CIFAR
    #     root_dir: /app/datasets/cifar100
    #     train: True
    #     ds_name: CIFAR100
    # validation_dataset:
    #     _target_: training.dataset_classes.lightning_datasets.CIFAR
    #     root_dir: /app/datasets/cifar100
    #     train: False
    #     ds_name: CIFAR100

    train_dataset:
        _target_: training.dataset_classes.lightning_datasets.CIFAR_N
        root_dir: /app/datasets/cifar10
        ds_name: CIFAR10
    validation_dataset:
        _target_: training.dataset_classes.lightning_datasets.CIFAR
        root_dir: /app/datasets/cifar10
        train: False
        ds_name: CIFAR10

    # train_dataset:
    #     _target_: training.dataset_classes.lightning_datasets.CIFAR_N
    #     root_dir: /app/datasets/cifar100
    #     ds_name: CIFAR100
    # validation_dataset:
    #     _target_: training.dataset_classes.lightning_datasets.CIFAR
    #     root_dir: /app/datasets/cifar100
    #     train: False
    #     ds_name: CIFAR100

    batch_size: 400
    num_workers: 20