seed_everything: 777
mode: train
trainer:
  _target_: pytorch_lightning.Trainer
  logger:
    _target_: pytorch_lightning.loggers.mlflow.MLFlowLogger
    experiment_name: "DUE SCF"
    run_name: "DUE SCF original ds"
  callbacks:
  - _target_: pytorch_lightning.callbacks.ModelCheckpoint 
    every_n_epochs: 1
    dirpath: outputs/due_scf_cifar10/noisy
    save_last: True
  - _target_: pytorch_lightning.callbacks.LearningRateMonitor
    logging_interval: "step"
  max_epochs: 40
  accelerator: gpu
  devices: 1
  num_sanity_val_steps: 0
  log_every_n_steps: 3
  default_root_dir: outputs/due_scf_cifar10/noisy
  enable_checkpointing: true
  

model:
    _target_: training.models.scf.SphereConfidenceFace
    backbone:
        _target_: training.models.lightning_wrappers.ResNet
        resnet_name: iresnet18_normalized
        weights: /app/model_weights/cifar10N/clean_backbone/resnet18.pt
        learnable: False
        fc_scale: 4
        num_features: 64
    head:
        _target_: training.models.heads.SCFHead
        convf_dim: 25088
        latent_vector_size: 4096
    scf_loss:
        _target_: training.models.losses.KLDiracVMF
        z_dim: 512
        radius: 64
    softmax_weights:
        _target_: training.models.scf.SoftmaxWeights
        softmax_weights_path: "/app/model_weights/cifar10N/clean_backbone/softmax_weights.pt"
        radius: 64
    optimizer_params:
        optimizer_path: torch.optim
        optimizer_name: AdamW
        params:
            lr: 3e-2
            weight_decay: 1e-1
    scheduler_params:
        scheduler: OneCycleLR
        params:
            max_lr: 3e-6
            steps_per_epoch: 125
            epochs: 40
            div_factor: 1e1
            final_div_factor: 1e1
        interval: step
    permute_batch: False


data:
    _target_: training.dataset_classes.lightning_datasets.UncertaintyDataModule
    train_dataset:
        _target_: training.dataset_classes.lightning_datasets.CIFAR_N
        root_dir: /app/datasets/cifar10
        ds_name: CIFAR10

    validation_dataset:
        _target_: training.dataset_classes.lightning_datasets.CIFAR
        root_dir: /app/datasets/cifar10
        train: False
        ds_name: CIFAR10
    batch_size: 400
    num_workers: 20