seed_everything: 777
mode: train
trainer:
  _target_: pytorch_lightning.Trainer
  logger:
    _target_: pytorch_lightning.loggers.mlflow.MLFlowLogger
    experiment_name: "HAAML"
    run_name: "HAAML ms1mv3"
  callbacks:
  - _target_: pytorch_lightning.callbacks.ModelCheckpoint 
    every_n_epochs: 1
    dirpath: outputs/haaml
    save_last: True
  - _target_: pytorch_lightning.callbacks.LearningRateMonitor
    logging_interval: "step"
  max_epochs: 32
  accelerator: gpu
  devices: 1
  num_sanity_val_steps: 0
  log_every_n_steps: 3
  default_root_dir: outputs/haaml
  enable_checkpointing: true
  

model:
    _target_: training.models.haaml.HAAMLModel
    backbone:
        _target_: training.models.lightning_wrappers.ResNet
        resnet_name: iresnet18_normalized
        weights: False
        learnable: True
    num_labels: 10572 # casia
    num_features: 512
    haaml_params:
        scale_size: 64
        m_0: 0.5
        t: 0.4
        loss_weight: 10
    optimizer_params:
        optimizer_path: torch.optim
        optimizer_name: SGD
        params:
            lr: 1e-1
            weight_decay: 5e-4
            momentum: 0.9
            nesterov: True
    scheduler_params:
        scheduler: MultiStepLR
        params:
            milestones: [8, 14, 20]
            gamma: 0.1
        interval: epoch
    #permute_batch: False


data:
    _target_: training.dataset_classes.lightning_datasets.UncertaintyDataModule
    train_dataset:
        _target_: training.dataset_classes.lightning_datasets.MXFaceDataset
        root_dir: /app/datasets/faces_webface_112x112
        torch_augments:
        - class_path: torchvision.transforms
          aug_name: RandomHorizontalFlip
          init_args: {}
        torch_probability: 1
    sampler:
        sampler_class: WeightedRandomSampler
        weights_path: /app/datasets/faces_webface_112x112/sampling_weights.npy

    batch_size: 256
    num_workers: 32