seed_everything: 777
mode: train
trainer:
  _target_: pytorch_lightning.Trainer
  logger:
    _target_: pytorch_lightning.loggers.WandbLogger
    project: "Data-unc-Models"
    name: "PFE-whale"
  callbacks:
  - _target_: pytorch_lightning.callbacks.ModelCheckpoint 
    every_n_epochs: 1
    dirpath: outputs/pfe_train/pfe_base_whale
    save_last: True
  - _target_: pytorch_lightning.callbacks.LearningRateMonitor
    logging_interval: "step"
  - _target_: training.models.scf.Prediction_writer
    output_dir: /app/cache/features
    file_name: pfe_whale
    write_interval: epoch
  max_epochs: 4
  accelerator: gpu
  devices: 1
  num_sanity_val_steps: 0
  log_every_n_steps: 3
  default_root_dir: outputs/pfe_train/pfe_base_whale
  enable_checkpointing: true
model:
    _target_: training.models.pfe.ProbabilisticFaceEmbedding
    backbone:
        _target_: training.models.lightning_wrappers.EfficientNet
        checkpoint_path: /app/model_weights/whale_arcface/last-v4.ckpt
        learnable: False
    head:
        _target_: training.models.heads.PFEHeadAdjustableLightning      
        in_feat: 776
        out_feat: 512
        learnable: True
    pfe_loss:
        _target_: training.models.losses.PFELoss
        mean: True
    optimizer_params:
        optimizer_path: torch.optim
        optimizer_name: AdamW
        params:
            lr: 3e-2
            weight_decay: 5e-4
    scheduler_params:
        scheduler: OneCycleLR
        params:
            max_lr: 3e-3
            steps_per_epoch: 3191
            epochs: 4
            div_factor: 1e1
            final_div_factor: 1e2
        interval: step
    permute_batch: False


data:
    _target_: training.dataset_classes.lightning_datasets.UncertaintyDataModule
    train_dataset:
        _target_: training.dataset_classes.lightning_datasets.WhaleDataset    
        config_path: /app/training/models/whale_arcface/config/efficientnet_b6_new.yaml
        image_dir: /app/datasets/whale_images
    train_batch_sampler:
        _target_: training.dataset_classes.samplers.PfeSampler
        batch_size: 16
        labels_path: /app/datasets/whale_images/labels.npy
    predict_dataset:
        _target_: training.dataset_classes.lightning_datasets.WhaleDataset    
        config_path: /app/training/models/whale_arcface/config/efficientnet_b6_new.yaml
        image_dir: /app/datasets/whale_images
        test: True
    batch_size: 16
    num_workers: 8