seed_everything: 777
mode: train
trainer:
  _target_: pytorch_lightning.Trainer
  logger:
    _target_: pytorch_lightning.loggers.mlflow.MLFlowLogger
    experiment_name: "SCF cosface glint360k"
    run_name: "base"
  callbacks:
  - _target_: pytorch_lightning.callbacks.ModelCheckpoint 
    every_n_epochs: 1
    dirpath: outputs/scf/scf_cosface_glint360k
    save_last: True
  - _target_: pytorch_lightning.callbacks.LearningRateMonitor
    logging_interval: "step"
  - _target_: training.models.scf.Prediction_writer
    output_dir: /app/cache/features/
    file_name: scf_2epoch_glint360k_ms1m_embs
    write_interval: epoch
  max_epochs: 2
  accelerator: gpu
  devices: 1
  num_sanity_val_steps: 0
  log_every_n_steps: 3
  default_root_dir: outputs/scf/scf_cosface_glint360k
  val_check_interval: 0.1
  enable_checkpointing: true
  
model:
    _target_: training.models.scf.SphereConfidenceFace
    backbone:
        _target_: training.models.lightning_wrappers.ResNet
        resnet_name: iresnet50_normalized
        weights: /app/model_weights/backbone/glint360k_cosface_r50_fp16_0.1/backbone.pth
        learnable: False
    head:
        _target_: training.models.heads.SCFHead
        convf_dim: 25088
        latent_vector_size: 4096
    scf_loss:
        _target_: training.models.losses.KLDiracVMF
        z_dim: 512
        radius: 64
    softmax_weights:
        _target_: training.models.scf.SoftmaxWeights
        softmax_weights_path: "/app/model_weights/backbone/glint360k_cosface_r50_fp16_0.1/softmax_weight.pt"
        radius: 64
    optimizer_params:
        optimizer_path: torch.optim
        optimizer_name: AdamW
        params:
            lr: 3e-2
            weight_decay: 5e-4
    scheduler_params:
        scheduler: OneCycleLR
        params:
            max_lr: 3e-4
            steps_per_epoch: 40694
            epochs: 2
            div_factor: 1e1
            final_div_factor: 1e2
        interval: step
    validation_dataset:
        _target_: training.dataset_classes.arcface_ijb.IJB_aligned_images
        dataset_path: /app/datasets/arcface_ijb/IJBC
        dataset_name: IJBC
        norm_image: True
    template_pooling_strategy:
        _target_: evaluation.template_pooling_strategies.PoolingConcentration
    recognition_method:
        _target_: evaluation.verification_methods.distance_based_verification.VerifEval
        distance_function:
            _target_: evaluation.distance_functions.distance_functions.CosineSimPairwise
    permute_batch: False
    verification_metrics:
        - _target_: evaluation.metrics.TarFar
          far_range: [-5, -0.5, 0.1]
          display_fars: [1e-5, 1e-4, 1e-3, 1e-2]
    verification_uncertainty_metrics:
        - _target_: evaluation.uncertainty_metrics.DisposeBasedOnUncVerif
          fractions: [0, 0.5, 10]
          metric_to_monitor:
            _target_: evaluation.metrics.TarFar
            far_range: [-5, -0.5, 0.1]
            display_fars: [1e-5, 1e-4, 1e-3, 1e-2]

data:
    _target_: training.dataset_classes.lightning_datasets.UncertaintyDataModule
    train_dataset:
        _target_: training.dataset_classes.lightning_datasets.MXFaceDataset
        root_dir: /app/datasets/glint360k
    validation_dataset:
        _target_: training.dataset_classes.arcface_ijb.IJB_aligned_images
        dataset_path: /app/datasets/arcface_ijb/IJBC
        dataset_name: IJBC
        norm_image: True

#    predict_dataset:
        # _target_: training.dataset_classes.arcface_ijb.IJB_aligned_images
        # dataset_path: /app/datasets/arcface_ijb/IJBC
        # dataset_name: IJBC
        # norm_image: True
    predict_dataset:
        _target_: training.dataset_classes.lightning_datasets.MXFaceDataset
        root_dir: /app/datasets/ms1m/
        test: True
        num_classes: 3531
    batch_size: 420
    num_workers: 20