seed_everything: 777
mode: train
trainer:
  _target_: pytorch_lightning.Trainer
  logger:
    _target_: pytorch_lightning.loggers.mlflow.MLFlowLogger
    experiment_name: "Text Recongition"
    run_name: "topic_dbpedia scf"
  callbacks:
  - _target_: pytorch_lightning.callbacks.ModelCheckpoint 
    every_n_epochs: 1
    dirpath: outputs/text_scf/topic_dbpedia
    save_last: True
  - _target_: pytorch_lightning.callbacks.LearningRateMonitor
    logging_interval: "step"
  - _target_: training.models.scf.Prediction_writer
    output_dir: /app/cache/features/
    file_name: scf_2epoch_topic_dbpedia_val_embs
    write_interval: epoch
  max_epochs: 2
  #precision: 16
  accelerator: gpu
  devices: 1
  num_sanity_val_steps: 0
  log_every_n_steps: 3
  default_root_dir: outputs/text_scf/topic_dbpedia
  enable_checkpointing: true
  

model:
    _target_: training.models.scf.SphereConfidenceFace
    backbone:
        _target_: training.models.lightning_wrappers.BERTEmbedder
        model_name: "bert-base-uncased"
        num_features: 768
        bottleneck_dim: 768
        freeze_projection: true
        freeze_backbone: true
        backbone_path: /app/model_weights/backbone/topic_dbpedia/backbone.pth
    head:
        _target_: training.models.heads.SCFHead
        convf_dim: 768
        latent_vector_size: 512
    scf_loss:
        _target_: training.models.losses.KLDiracVMF
        z_dim: 768
        radius: 1.
    softmax_weights:
        _target_: training.models.scf.SoftmaxWeights
        softmax_weights_path: "/app/model_weights/backbone/topic_dbpedia/softmax_weight.pt"
        radius: 1
    optimizer_params:
        optimizer_path: torch.optim
        optimizer_name: AdamW
        params:
          lr: 1e-3
          weight_decay: 1e-4
    scheduler_params:
        scheduler: OneCycleLR
        params:
          max_lr: 1e-4
          steps_per_epoch: 625  
          epochs: 2
          div_factor: 10
          final_div_factor: 10
        interval: step
    permute_batch: false


data:
    _target_: training.dataset_classes.text_datasets.TextDatasets
    tokenizer_name: "bert-base-uncased"
    train_dataset:
        _target_: training.dataset_classes.text_datasets.TextClassificationDataset
        root_dir: /app/datasets/text_datasets/dbpedia_csv
    # predict_dataset:
    #     _target_: training.dataset_classes.text_datasets.TextPredictionDataset
    #     root_dir: /app/datasets/text-ident/dbpedia
    predict_dataset:
        _target_: training.dataset_classes.text_datasets.TextPredictionDataset
        root_dir: /app/datasets/text-ident-val/dbpedia-val
    batch_size: 512
    max_length: 512
    num_workers: 32