seed_everything: 777
mode: train
trainer:
  _target_: pytorch_lightning.Trainer
  logger:
    _target_: pytorch_lightning.loggers.mlflow.MLFlowLogger
    experiment_name: "PAN Authorship Recognition"
    run_name: "bert scf 4k"
  callbacks:
  - _target_: pytorch_lightning.callbacks.ModelCheckpoint 
    every_n_epochs: 1
    dirpath: outputs/text_scf/pan_4k
    save_last: True
  - _target_: pytorch_lightning.callbacks.LearningRateMonitor
    logging_interval: "step"
  - _target_: training.models.scf.Prediction_writer
    output_dir: /app/cache/features/
    file_name: pan_test_embs
    write_interval: epoch
  max_epochs: 8
  accelerator: gpu
  devices: 1
  num_sanity_val_steps: 0
  log_every_n_steps: 3
  default_root_dir: outputs/text_scf/pan_4k
  enable_checkpointing: true
  

model:
    _target_: training.models.scf.SphereConfidenceFace
    backbone:
        _target_: training.models.lightning_wrappers.BERTEmbedder
        model_name: "bert-base-uncased"
        num_features: 768
        bottleneck_dim: 2048
        freeze_projection: true
        freeze_backbone: true
        proj_depth: 2
        backbone_path: /app/model_weights/backbone/bert_pan_4k/backbone.pth
    head:
        _target_: training.models.heads.SCFHead
        convf_dim: 2048
        latent_vector_size: 512
    scf_loss:
        _target_: training.models.losses.KLDiracVMF
        z_dim: 768
        radius: 1.
    softmax_weights:
        _target_: training.models.scf.SoftmaxWeights
        softmax_weights_path: "/app/model_weights/backbone/bert_pan_4k/softmax_weight.pt"
        radius: 1
    optimizer_params:
        optimizer_path: torch.optim
        optimizer_name: AdamW
        params:
          lr: 1e-3
          weight_decay: 1e-4
    scheduler_params:
        scheduler: OneCycleLR
        params:
          max_lr: 1e-3
          steps_per_epoch: 162  
          epochs: 8
          div_factor: 10
          final_div_factor: 100
        interval: step
    permute_batch: false

data:
  _target_: training.dataset_classes.pan_text.PANDataModule
  train_jsonl: "/app/datasets/pan/unseen_authors/xl/pan20-av-large-notest.jsonl"
  test_jsonl: "/app/datasets/pan/unseen_authors/xl/pan20-av-large-test.jsonl"
  tokenizer_name: "bert-base-uncased"
  batch_size: 512 
  num_workers: 16
  max_length: 512
  min_docs_per_author: 10 # 20 for train    
  train_authors: 4000
  val_authors: 1000
  val_probe_authors: 1000
  test_authors : 1000
  test_probe_authors: 1000
  predict_on_split: test
