seed_everything: 777
mode: train
trainer:
  _target_: pytorch_lightning.Trainer
  logger:
    _target_: pytorch_lightning.loggers.mlflow.MLFlowLogger
    experiment_name: "Text Recongition"
    run_name: "bert arcface"
  callbacks:
  - _target_: pytorch_lightning.callbacks.ModelCheckpoint 
    every_n_epochs: 1
    dirpath: outputs/bert_arcface_yahoo
    save_last: True
  - _target_: pytorch_lightning.callbacks.LearningRateMonitor
    logging_interval: "step"
  max_epochs: 2
  precision: 16
  accelerator: gpu
  devices: 1
  num_sanity_val_steps: 0
  log_every_n_steps: 3
  default_root_dir: outputs/bert_arcface_yahoo
  enable_checkpointing: true
  

model:
    _target_: training.models.arcface.MetricLearningModel
    backbone:
      _target_: training.models.lightning_wrappers.BERTEmbedder
      model_name: "bert-base-uncased"
      num_features: 768
      bottleneck_dim: 768
      projection: True    # keep it simple for now; set true if you want extra projection
      freeze_backbone: False
    loss:
        _target_: training.models.losses.ArcFaceLoss
        s: 64
    num_labels: 6
    num_features: 768
    optimizer_params:
        optimizer_path: torch.optim
        optimizer_name: SGD
        params:
            lr: 1e-1
            weight_decay: 5e-4
            momentum: 0.9
            nesterov: True
    scheduler_params:
        scheduler: OneCycleLR
        params:
            max_lr: 1e-2
            steps_per_epoch: 6562
            epochs: 2
            div_factor: 1e1
            final_div_factor: 1e2
        interval: step


data:
    _target_: training.dataset_classes.text_datasets.TextDatasets
    tokenizer_name: "bert-base-uncased"
    train_dataset:
        _target_: training.dataset_classes.text_datasets.TextClassificationDataset
        root_dir: /app/datasets/text_datasets/yahoo_answers_csv
    batch_size: 128
    num_workers: 32