seed_everything: 777
mode: train
trainer:
  _target_: pytorch_lightning.Trainer
  logger:
    _target_: pytorch_lightning.loggers.WandbLogger
    project: "SCF-VB2"
    name: "PFE-Base"
  callbacks:
  - _target_: pytorch_lightning.callbacks.ModelCheckpoint 
    every_n_epochs: 1
    dirpath: outputs/pfe_vb2
    save_last: True
  - _target_: pytorch_lightning.callbacks.LearningRateMonitor
    logging_interval: "step"
  max_epochs: 2
  accelerator: gpu
  devices: 1
  num_sanity_val_steps: 0
  log_every_n_steps: 3
  default_root_dir: outputs/pfe_vb2
  val_check_interval: 0.1
  enable_checkpointing: true
model:
    _target_: training.models.pfe.ProbabilisticFaceEmbedding
    backbone:
        _target_: training.models.lightning_wrappers.EmbModel
    head:
        _target_: training.models.heads.PFEHeadAdjustableLightning
        in_feat: 1024
        out_feat: 256
        learnable: True
    pfe_loss:
        _target_: training.models.losses.PFELoss
        mean: True
    optimizer_params:
        optimizer_path: torch.optim
        optimizer_name: AdamW
        params:
            lr: 3e-2 #3e-5
            weight_decay: 5e-4
    scheduler_params:
            # scheduler: StepLR
            # params:
            #     step_size: 2
            #     gamma: 0.1
        scheduler: OneCycleLR
        params:
            max_lr: 3e-2
            steps_per_epoch: 2629
            epochs: 2
            div_factor: 1e1
            final_div_factor: 1e2
        interval: step
    permute_batch: False


data:
    _target_: training.dataset_classes.lightning_datasets.UncertaintyDataModule
    train_dataset:
        _target_: training.dataset_classes.lightning_datasets.VoxBlinkEmbeddingsDataset
        root_dir: /app/datasets/VB2_11_embs

    batch_size: 1060
    num_workers: 20