seed_everything: 777
mode: train
trainer:
  _target_: pytorch_lightning.Trainer
  logger:
    _target_: pytorch_lightning.loggers.WandbLogger
    project: "Whale-train"
    name: "ScfEmbs"
  callbacks:
  - _target_: pytorch_lightning.callbacks.ModelCheckpoint 
    every_n_epochs: 1
    dirpath: outputs/scf_whale_embs
    save_last: True
  - _target_: pytorch_lightning.callbacks.LearningRateMonitor
    logging_interval: "step"
  max_epochs: 4
  accelerator: gpu
  devices: 1
  num_sanity_val_steps: 0
  log_every_n_steps: 3
  default_root_dir: outputs/scf_whale_embs
  enable_checkpointing: true
model:
    _target_: training.models.scf.SphereConfidenceFace
    backbone:
        _target_: training.models.lightning_wrappers.EmbModel
    head:
        _target_: training.models.heads.SCFHead
        convf_dim: 776
        latent_vector_size: 4096
    scf_loss:
        _target_: training.models.losses.KLDiracVMF
        z_dim: 512
        radius: 64
    softmax_weights:
        _target_: training.models.scf.SoftmaxWeights
        softmax_weights_path: "/app/datasets/whale_embs/softmax_weight.pt"
        radius: 64
    optimizer_params:
        optimizer_path: torch.optim
        optimizer_name: AdamW
        params:
            lr: 3e-2
            weight_decay: 5e-4
    scheduler_params:
        scheduler: OneCycleLR
        params:
            max_lr: 3e-4
            steps_per_epoch: 256 
            epochs: 4
            div_factor: 1e1
            final_div_factor: 1e2
        interval: step
    permute_batch: False


data:
    _target_: training.dataset_classes.lightning_datasets.UncertaintyDataModule
    train_dataset:
        _target_: training.dataset_classes.lightning_datasets.WhaleEmbeddingsDataset    
        root_dir: /app/datasets/whale_embs

    # predict_dataset:
    #     _target_: training.dataset_classes.lightning_datasets.WhaleDataset    
    #     config_path: /app/training/models/whale_arcface/config/efficientnet_b6_new.yaml
    #     image_dir: /app/datasets/whale_images
    #     test: True

    batch_size: 200
    num_workers: 4